### ISSUE TITLE
Error: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by efrainceh** [Merck/BioPhi#42]
I got this message while trying to Export a Full Table after humanization.

![image](https://github.com/Merck/BioPhi/assets/68831860/ed75aae5-43af-442e-a3cb-45ba35e3a631)

**Comment by gracejacobson** [comment]
Hi, I was using biophi from command line and also got this error. I fixed it by going to line 83 of biophi/humanization/methods/humanness.py:

`
curve = curve.astype(np.int64)
`

**Comment by efrainceh** [comment]
Ok, thanks!

**Comment by gracejacobson** [comment]
No problem. I think it has to do with the version of numpy since I didn't have any issues when I set up the conda environment for biophi in the readme.

**Comment by tony-res** [comment]
I created a pull request to fix.

**Comment by eliottpark** [comment]
Hi @tony-res, I am building this package using conda and am still getting this same error.

I took a look at [line 83 under the most up to date version tag (1.0.9) ](https://github.com/Merck/BioPhi/blob/v1.0.9/biophi/humanization/methods/humanness.py#L83) and it seems to still have the old `np.int` implementation. It seems like the latest version tag is not up to date with the main branch. Any chance you'd be able to release a new version from the current main branch and subsequently publish to bioconda? 

Many thanks!
